from django.db import models


class Trip(models.Model):
	"""A saved trip plan generated by the HOS engine."""
	created_at = models.DateTimeField(auto_now_add=True)
	start_time = models.DateTimeField()
	current_location = models.CharField(max_length=255)
	pickup_location = models.CharField(max_length=255)
	dropoff_location = models.CharField(max_length=255)
	current_cycle_used = models.FloatField()

	total_miles = models.FloatField(null=True, blank=True)
	total_driving_hours = models.FloatField(null=True, blank=True)
	total_on_duty_hours = models.FloatField(null=True, blank=True)
	total_off_duty_hours = models.FloatField(null=True, blank=True)
	final_cycle_hours = models.FloatField(null=True, blank=True)

	def __str__(self):
		return f"Trip {self.id}: {self.current_location} → {self.dropoff_location} ({self.start_time.date()})"


class Segment(models.Model):
	trip = models.ForeignKey(Trip, related_name="segments", on_delete=models.CASCADE)
	status = models.CharField(max_length=8)
	start = models.DateTimeField()
	end = models.DateTimeField()
	label = models.CharField(max_length=255, blank=True)

	@property
	def hours(self):
		return (self.end - self.start).total_seconds() / 3600.0

	def __str__(self):
		return f"{self.status} {self.start.isoformat()}-{self.end.isoformat()}"
