# Generated by Django 6.0.7 on 2026-07-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField()),
                ('total_miles', models.FloatField(blank=True, null=True)),
                ('total_driving_hours', models.FloatField(blank=True, null=True)),
                ('total_on_duty_hours', models.FloatField(blank=True, null=True)),
                ('total_off_duty_hours', models.FloatField(blank=True, null=True)),
                ('final_cycle_hours', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=8)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='planner.trip')),
            ],
        ),
    ]
